name: The Riveros
favicon: null
layout_spectrum: 0.5111180660314858
typography_spectrum: 0.47291892068460584
title: 'Life. And what it brings. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.809783827746287
  lightness: 0.2593527468852699
  saturation: 0.09375465684570372
  rhythmicContrast: 0.3838522145524621
purpose: []
